%% env log
varnames{1} = {'USE_DEVICE',...
    'SAMPLERATE','NRUNS',...
    'info',...
    'key',...
    'dspl','cursor','RATINGTITLES',...
    'run',...
    'DURATION',...
    'ratings',...
    'ttlist','tt',...
    'timings','timing','t',...
    'onsets','onset','o',...
    'oratings','cratings'};

varnames{2} = {'info','timings','t','timing','tt','oratings','cratings','trials','ratings','prqlog'};

fout = {envlogfile logfile};

for f = 1:numel(varnames)
    cmdstr = sprintf('save(''%s''',[fout{f} '_emergencysave']);
    for i = 1:numel(varnames{f})
        if exist(varnames{f}{i},'var')
            cmdstr = [cmdstr ',''' varnames{f}{i} ''''];
        end
    end
    cmdstr = [cmdstr ');'];
    
    fprintf('Saving: %s\n',cmdstr);
    eval(cmdstr);
end
