function [ts, post_q] = generate_ts_mpa2_part2_capsaicin

% ts = generate_ts_mpa2_part2

ts{1}{1} = {'REST', 'LV0', '0000', {'overall_avoidance'}, '0', '0', '7'};
for i = 2:11
    ts{1}{i} = {'REST', 'LV0', '0023', {'overall_avoidance'}, '0', '0', '7'};
end

post_q{1} = {'overall_relaxed', ...
    'overall_attention',...
    'overall_boredness', ...
    'overall_alertness', ...
    'overall_resting_positive', ...
    'overall_resting_negative', ...
    'overall_resting_myself', ...
    'overall_resting_others', ...
    'overall_resting_imagery', ...
    'overall_resting_present', ...
    'overall_resting_past', ...
    'overall_resting_future', ...
    'overall_resting_capsai_int', ...
    'overall_resting_capsai_unp'};

end