function [R2,beta,intercept,F,df_reg,df_err,pvalue] = regplot(XYmat,plottitle);
% This function computes a simple linear regression between the stimulation
% given (X) and the ratings (Y). The plot generated shows the R-squared
% value, F-value and p-value for the regression. The input X will contain
% the values generated by the experiment for pain (tenperatures), taste
% (concentrations) and vision (levels).

% Compute regression statistics
X = XYmat(:,1);
Y = XYmat(:,2);
STATS = regstats(Y,X-mean(X),'linear',{'rsquare','beta','fstat'});
intercept = STATS.beta(1); % Intercept
beta = STATS.beta(2); % Regression Coefficient
R2 = STATS.rsquare; % R-squared
F = STATS.fstat.f; % F-value
df_reg = STATS.fstat.dfr; % Degrees of Freedom Regression
df_err = STATS.fstat.dfe; % Degrees of Freedom Error/Residual
pvalue = STATS.fstat.pval; % p-vlaue

% Plot regression line
figure()
axis square
scatter(X,Y) % Scatter plot of X against Y
lsline % Least-Squares (regression ) line
title(strcat('Overall Rating - ', plottitle))
xlabel('Level of Sensation')
ylabel('Ratings')
set(gca,'XTick',min(X):1:max(X))
set(gca,'YTick',min(Y):10:max(Y))
xlim([min(X) max(X)])
ylim([0 100])

% Display R-square, F and p-value on plot
text(min(xlim)+0.10, max(ylim)-2, strcat('Rating = ',...
  num2str(intercept),' + ', num2str(beta), '* Stimulation'))
text(min(xlim)+0.10, max(ylim)-6, strcat('R-squared = ', num2str(R2)))
%text(min(xlim)+0.10, max(ylim)-10, strcat('F-value = ', num2str(F)))
%text(min(xlim)+0.10, max(ylim)-14, strcat('p-value = ', num2str(pvalue)))
